import { type NextPage } from "next";
import Head from "next/head";
import { Button } from "~/components/Button";
import { Input } from "~/components/Input";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Drizzle - Edge Shortener</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen bg-gray-800">
        <div className="flex h-full flex-col items-center justify-center">
          <h1 className="text-4xl font-bold text-gray-200">Drizzle</h1>
          <p className="text-gray-400">Edge Shortener</p>

          <form className="flex items-center pt-4">
            <Input placeholder="https://example.com" />
            <Button type="submit">Shorten</Button>
          </form>
        </div>
      </main>
    </>
  );
};

export default Home;
